version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_commits:
  files:
    - '*.md'
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Win32
install:
- ps: |
    # install cmake 3.13 or better
    # REMOVE THIS when AppVeyor updates CMake
    iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
    scoop install cmake

    # init submodules recusivelly
    git submodule update --init --recursive

    # versioning vars
    $env:GIT_COMMIT_HASH = $(git rev-parse --short=8 HEAD)
    $env:LAUNCHER_VERSION = $(Get-Content .\version.txt)

    # generate project files
    cmake -G "Visual Studio 15 2017" ./
build:
  project: launcher.sln
  verbosity: minimal
after_build:
- ps: |    
    if ($env:CONFIGURATION -eq 'Release') {
      $artifactPrefix = $env:APPVEYOR_PROJECT_NAME + "_" + $env:LAUNCHER_VERSION + "-" + $env:APPVEYOR_REPO_BRANCH + "-" + $env:GIT_COMMIT_HASH + "-" + $env:CONFIGURATION
      7z a -m0=lzma2 -mx9 $($artifactPrefix + "_binaries.7z") $env:APPVEYOR_BUILD_FOLDER\out\bin\Win32\Release\launcher.exe `
        $env:APPVEYOR_BUILD_FOLDER\start-cso2.bat
      7z a -m0=lzma2 -mx9 $($artifactPrefix + "_symbols.7z") $env:APPVEYOR_BUILD_FOLDER\out\bin\Win32\Release\launcher.pdb
    }
test: off
artifacts:
- path: $(APPVEYOR_PROJECT_NAME)_$(LAUNCHER_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(GIT_COMMIT_HASH)_Release-binaries.7z
  name: binaries
- path: $(APPVEYOR_PROJECT_NAME)_$(LAUNCHER_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(GIT_COMMIT_HASH)_Release-symbols.7z
  name: symbols
deploy:
- provider: GitHub
  release: Build $(LAUNCHER_VERSION)-$(GIT_COMMIT_HASH)-$(APPVEYOR_REPO_BRANCH)
  auth_token:
    secure: XnUsE3jqzulQ4cWVkK2ALBR7qfnfwbBdoMDChmcnx1RcGtRgXV0QLMPo+GcIf8YU
  artifact: binaries,symbols
  on:
    branch: master
    configuration: Release
on_success:
- ps: |
    # set appveyor build version
    update-appveyorbuild -version $env:LAUNCHER_VERSION-$env:APPVEYOR_REPO_BRANCH-$env:GIT_COMMIT_HASH