version: 0.4.1-{build}
pull_requests:
  do_not_increment_build_number: true

image:
  - Visual Studio 2019

environment:
  matrix:
    #- BUILD_COMBO: windows-mingw
    - BUILD_COMBO: windows-msvc
    - BUILD_COMBO: windows-clang_cl

configuration:
  - Debug
  - Release

install:
  - ps: ./ci/setup.ps1

build_script:
  - ps: ./ci/build.ps1

after_build:
  - ps: ./ci/pack.ps1
  - ps: $env:VERSION_STR = Get-Content -Path ./version.txt -TotalCount 1

artifacts:
#- path: build/cso2_launcher-*-win64_mingw.7z
#  name: mingw_binaries
- path: build/cso2_launcher-*-win64_msvc.7z
  name: msvc_binaries
- path: build/cso2_launcher-*-win64_clang.7z
  name: clang_binaries

test: off

deploy:
- provider: GitHub
  release: Version $(VERSION_STR)
  auth_token:
    secure: XnUsE3jqzulQ4cWVkK2ALBR7qfnfwbBdoMDChmcnx1RcGtRgXV0QLMPo+GcIf8YU
  artifact: clang_binaries
  on:
    APPVEYOR_REPO_TAG: true
    configuration: Release
