version: 0.2.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_commits:
  files:
    - '*.md'
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x86
install:
- ps: >-
    iex (new-object net.webclient).downloadstring('https://get.scoop.sh')

    scoop install cmake

    git submodule update --init --recursive

    $env:GIT_COMMIT_HASH = $(git rev-parse --short=8 HEAD)

    $env:GIT_BRANCH = $(git rev-parse --abbrev-ref HEAD)

    $env:LAUNCHER_VERSION = $(Get-Content .\version.txt)

    cmake -G "Visual Studio 15 2017" ./
build:
  project: launcher.sln
  verbosity: minimal
after_build:
- ps: >-
    if ($env:CONFIGURATION -eq 'Release') {
      7z a $env:APPVEYOR_PROJECT_NAME_$env:LAUNCHER_VERSION-$env:GIT_COMMIT_HASH-$env:GIT_BRANCH-$env:CONFIGURATION_binaries.zip $env:APPVEYOR_BUILD_FOLDER\out\bin\Win32\Release\launcher.exe
      7z a $env:APPVEYOR_PROJECT_NAME_$env:LAUNCHER_VERSION-$env:GIT_COMMIT_HASH-$env:GIT_BRANCH-$env:CONFIGURATION_binaries.zip $env:APPVEYOR_BUILD_FOLDER\start-cso2.bat
      7z a $env:APPVEYOR_PROJECT_NAME_$env:LAUNCHER_VERSION-$env:GIT_COMMIT_HASH-$env:GIT_BRANCH-$env:CONFIGURATION_symbols.zip $env:APPVEYOR_BUILD_FOLDER\out\bin\Win32\Release\launcher.pdb
    }
test: off
artifacts:
- path: $env:APPVEYOR_PROJECT_NAME_$env:LAUNCHER_VERSION-$env:GIT_COMMIT_HASH-$env:GIT_BRANCH-Release_binaries.zip
  name: binaries
- path: $env:APPVEYOR_PROJECT_NAME_$env:LAUNCHER_VERSION-$env:GIT_COMMIT_HASH-$env:GIT_BRANCH-Release-symbols.zip
  name: symbols
deploy:
- provider: GitHub
  release: Build $env:LAUNCHER_VERSION-$env:GIT_COMMIT_HASH-$env:GIT_BRANCH
  auth_token:
    secure: XnUsE3jqzulQ4cWVkK2ALBR7qfnfwbBdoMDChmcnx1RcGtRgXV0QLMPo+GcIf8YU
  artifact: binaries,symbols
  on:
    branch: master
    configuration: Release